apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8guard-kafka
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8guard-kafka
{{ if .Values.kafka.labels }}
{{ toYaml .Values.kafka.labels | indent 8 }}
{{ end }}
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        # image: satlank/microzookeeper:3.4.9-1
        ports:
        - containerPort: 2181
{{ if .Values.zookeeper.resources }}
        resources:
{{ toYaml .Values.zookeeper.resources | indent 10}}
{{- end }}
      - name: kafka
        image: wurstmeister/kafka:0.10.2.1
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "localhost:2181"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "k8guard-kafka-service.default.svc.cluster.local"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_CREATE_TOPICS
            value: "k8guard-to-action-k8s-lab:1:1"
        ports:
        - containerPort: 9092
{{ if .Values.kafka.resources }}
        resources:
{{ toYaml .Values.kafka.resources | indent 10 }}
{{- end }}
