apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8guard-memcached
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8guard-memcached
{{ if .Values.memcached.labels }}
{{- toYaml .Values.memcached.labels | indent 8 }}
{{ end }}
    spec:
      containers:
      - name: k8guard-memcached
        image: memcached:alpine
{{ if .Values.memcached.resources }}
        resources:
{{- end }}
{{ toYaml .Values.memcached.resources | indent 10 }}
