apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8guard-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8guard-redis
{{ if .Values.redis.labels }}
{{- toYaml .Values.redis.labels | indent 8 }}
{{ end }}
    spec:
      containers:
      - name: k8guard-redis
        image: redis:alpine
        ports:
        - containerPort: 6379
{{ if .Values.redis.resources }}
        resources:
{{ toYaml .Values.redis.resources | indent 10 }}
{{- end }}
